-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.2.0
-- Generated: 2016-12-22 14:39

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_codecombat_identify_1 (
    "schema_vendor"                       VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                         VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"                       VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"                      VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                             CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                         TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                            VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                            VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                          VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "user"                                CHAR(24)      ENCODE LZO       NOT NULL,
    "id"                                  VARCHAR(4096) ENCODE LZO,
    "traits.age_range"                    VARCHAR(4096) ENCODE LZO,
    "traits.announces_action_audio_group" VARCHAR(4096) ENCODE LZO,
    "traits.anonymous"                    BOOLEAN       ENCODE RUNLENGTH,
    "traits.date_created"                 TIMESTAMP     ENCODE LZO,
    "traits.default_language_group"       VARCHAR(4096) ENCODE LZO,
    "traits.email"                        VARCHAR(4096) ENCODE LZO,
    "traits.gender"                       VARCHAR(6)    ENCODE LZO,
    "traits.host"                         VARCHAR(4096) ENCODE LZO,
    "traits.hour_of_code"                 BOOLEAN       ENCODE RUNLENGTH,
    "traits.last_level"                   VARCHAR(4096) ENCODE LZO,
    "traits.name"                         VARCHAR(4096) ENCODE LZO,
    "traits.priority"                     VARCHAR(4096) ENCODE LZO,
    "traits.referrer"                     VARCHAR(4096) ENCODE LZO,
    "traits.role"                         VARCHAR(4096) ENCODE LZO,
    "traits.school_name"                  VARCHAR(4096) ENCODE LZO,
    "traits.teacher"                      BOOLEAN       ENCODE RUNLENGTH,
    "traits.test_group_number"            BIGINT        ENCODE LZO,
    "traits.year_subscription_group"      VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_codecombat_identify_1 IS 'iglu:com.codecombat/identify/jsonschema/1-0-0';
