-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.4.0
-- Generated: 2018-03-08 14:52 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_codecombat_levelloaderror_2 (
    "schema_vendor"  VARCHAR(128)   ENCODE ZSTD NOT NULL,
    "schema_name"    VARCHAR(128)   ENCODE ZSTD NOT NULL,
    "schema_format"  VARCHAR(128)   ENCODE ZSTD NOT NULL,
    "schema_version" VARCHAR(128)   ENCODE ZSTD NOT NULL,
    "root_id"        CHAR(36)       ENCODE RAW  NOT NULL,
    "root_tstamp"    TIMESTAMP      ENCODE ZSTD NOT NULL,
    "ref_root"       VARCHAR(255)   ENCODE ZSTD NOT NULL,
    "ref_tree"       VARCHAR(1500)  ENCODE ZSTD NOT NULL,
    "ref_parent"     VARCHAR(255)   ENCODE ZSTD NOT NULL,
    "unloaded"       VARCHAR(65535) ENCODE ZSTD NOT NULL,
    "user"           CHAR(24)       ENCODE ZSTD NOT NULL,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_codecombat_levelloaderror_2 IS 'iglu:com.codecombat/levelloaderror/jsonschema/2-0-0';
